// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSG6EcrE0JxixDwI888wKqEmYSWu91Vw8',
    appId: '1:779857664423:web:8cc65ed9e9fad10da47e82',
    messagingSenderId: '779857664423',
    projectId: 'crudtut-7cdd1',
    authDomain: 'crudtut-7cdd1.firebaseapp.com',
    storageBucket: 'crudtut-7cdd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnG9JS35Pup5lH8j_UFVcGGYzF3zjrtI',
    appId: '1:779857664423:android:0fa53e7b1640894ba47e82',
    messagingSenderId: '779857664423',
    projectId: 'crudtut-7cdd1',
    storageBucket: 'crudtut-7cdd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALJ1Ajg6mowjYSG7R_GAcipKmOvvUaxv0',
    appId: '1:779857664423:ios:0241842770fa6d81a47e82',
    messagingSenderId: '779857664423',
    projectId: 'crudtut-7cdd1',
    storageBucket: 'crudtut-7cdd1.appspot.com',
    iosBundleId: 'com.example.crudTut',
  );
}
